### ISSUE TITLE
Change Result -> bundleId to string

### ISSUE THREAD

**Issue by MallorcaSoftware** [mdewilde/itunes-search#2]
BundleId is a string value.

**Comment by mdewilde** [comment]
Thanks for the report.

Would you have a sample lookup or search that returns a bundleId that is not a String?

**Comment by MallorcaSoftware** [comment]
No bundleId is always a string (i guess) but your Result class has Long bundleId.

src/main/java/be/ceau/itunesapi/response/Result.java Line 40

```
Response response = new Search("facebook")
                .setCountry(Country.GERMANY)
                .setMedia(Media.SOFTWARE)
                .setLimit(15)
                .execute();
```

Results in: 
`Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.lang.Long` from String "com.facebook.Facebook": not a valid Long value`
