### ISSUE TITLE
Search Request

### ISSUE THREAD

**Issue by Cyclone1337** [mdewilde/itunes-search#7]
Hey i have the following problem with the search api:
i want to request this term "term=podcast&limit=10&genreID=1303",
but the response don't found any results.

I think the problem is the "StandardCharsets.UTF_8.name()" in termParam() and in the get()-Method in the URLConnector.
I tried to change the "&" in the term with the utf-8 code \u0026, but it doesn't work.
An equal term with term=1303 and the attribute=genreIndex also doesn't work.

So what should i write that i get this expected result:

`{
 "resultCount":10,
 "results": [
{"wrapperType":"track", "kind":"podcast", "artistId":974891224, "collectionId":360084272, "trackId":360084272, "artistName":"Joe Rogan", "collectionName":"The Joe Rogan Experience", "trackName":"The Joe Rogan Experience", "collectionCensoredName":"The Joe Rogan Experience", "trackCensoredName":"The Joe Rogan Experience", "artistViewUrl":"https://podcasts.apple.com/us/artist/joe-rogan/974891224?uo=4", "collectionViewUrl":"https://podcasts.apple.com/us/podcast/the-joe-rogan-experience/id360084272?uo=4", "feedUrl":"http://joeroganexp.joerogan.libsynpro.com/rss", "trackViewUrl":"https://podcasts.apple.com/us/podcast/the-joe-rogan-experience/id360084272?uo=4", "artworkUrl30":"https://is5-ssl.mzstatic.com/image/thumb/Podcasts123/v4/12/ab/d6/12abd655-2473-c4fb-7d53-33e1b9e4afdc/mza_6788052308516976968.jpg/30x30bb.jpg", "artworkUrl60":"https://is5-ssl.mzstatic.com/image/thumb/Podcasts123/v4/12/ab/d6/12abd655-2473-c4fb-7d53-33e1b9e4afdc/mza_6788052308516976968.jpg/60x60bb.jpg", "artworkUrl100":"https://is5-ssl.mzstatic.com/image/thumb/Podcasts123/v4/12/ab/d6/12abd655-2473-c4fb-7d53-33e1b9e4afdc/mza_6788052308516976968.jpg/100x100bb.jpg", "collectionPrice":0.00, "trackPrice":0.00, "trackRentalPrice":0, "collectionHdPrice":0, "trackHdPrice":0, "trackHdRentalPrice":0, "releaseDate":"2019-12-10T02:30:00Z", "collectionExplicitness":"explicit", "trackExplicitness":"explicit", "trackCount":300, "country":"USA", "currency":"USD", "primaryGenreName":"Comedy", "contentAdvisoryRating":"Explicit", "artworkUrl600":"https://is5-ssl.mzstatic.com/image/thumb/Podcasts123/v4/12/ab/d6/12abd655-2473-c4fb-7d53-33e1b9e4afdc/mza_6788052308516976968.jpg/600x600bb.jpg", "genreIds":["1303", "26", "1324"], "genres":["Comedy", "Podcasts", "Society & Culture"]}, 
{"wrapperType":"track", "kind":"podcast", "artistId":364380278, "collectionId":201671138, "trackId":201671138, "artistName":"This American Life", "collectionName":"This American Life", "trackName":"This American Life", "collectionCensoredName":"This American Life", "trackCensoredName":"This American Life", "artistViewUrl":"https://podcasts.apple.com/us/artist/wbez/364380278?uo=4", "collectionViewUrl":"https://podcasts.apple.com/us/podcast/this-american-life/id201671138?uo=4", "feedUrl":"http://feed.thisamericanlife.org/talpodcast", "trackViewUrl":"https://podcasts.apple.com/us/podcast/this-american-life/id201671138?uo=4", "artworkUrl30":"https://is1-ssl.mzstatic.com/image/thumb/Podcasts123/v4/4e/b9/bb/4eb9bb9b-ed19-f0b7-7739-1177f1b35207/mza_8452563123961176873.png/30x30bb.jpg", "artworkUrl60":"https://is1-ssl.mzstatic.com/image/thumb/Podcasts123/v4/4e/b9/bb/4eb9bb9b-ed19-f0b7-7739-1177f1b35207/mza_8452563123961176873.png/60x60bb.jpg", "artworkUrl100":"https://is1-ssl.mzstatic.com/image/thumb/Podcasts123/v4/4e/b9/bb/4eb9bb9b-ed19-f0b7-7739-1177f1b35207/mza_8452563123961176873.png/100x100bb.jpg", "collectionPrice":0.00, "trackPrice":0.00, "trackRentalPrice":0, "collectionHdPrice":0, "trackHdPrice":0, "trackHdRentalPrice":0, "releaseDate":"2019-12-08T23:00:00Z", "collectionExplicitness":"notExplicit", "trackExplicitness":"notExplicit", "trackCount":10, "country":"USA", "currency":"USD", "primaryGenreName":"Personal Journals", "artworkUrl600":"https://is1-ssl.mzstatic.com/image/thumb/Podcasts123/v4/4e/b9/bb/4eb9bb9b-ed19-f0b7-7739-1177f1b35207/mza_8452563123961176873.png/600x600bb.jpg", "genreIds":["1302", "26", "1324", "1301"], "genres":["Personal Journals", "Podcasts", "Society & Culture", "Arts"]}, 
{"wrapperType":"track", "kind":"podcast", "artistId":284341002, "collectionId":278981407, "trackId":278981407, "artistName":"iHeartRadio & HowStuffWorks", "collectionName":"Stuff You Should Know", "trackName":"Stuff You Should Know", "collectionCensoredName":"Stuff You Should Know", "trackCensoredName":"Stuff You Should Know", "artistViewUrl":"https://podcasts.apple.com/us/artist/iheartradio/284341002?uo=4", "collectionViewUrl":"https://podcasts.apple.com/us/podcast/stuff-you-should-know/id278981407?uo=4", "feedUrl":"https://feeds.megaphone.fm/stuffyoushouldknow", "trackViewUrl":"https://podcasts.apple.com/us/podcast/stuff-you-should-know/id278981407?uo=4", "artworkUrl30":"https://is2-ssl.mzstatic.com/image/thumb/Podcasts113/v4/f8/4f/87/f84f8705-6640-a010-29a5-09a23195e41c/mza_453847711009197462.png/30x30bb.jpg", "artworkUrl60":"https://is2-ssl.mzstatic.com/image/thumb/Podcasts113/v4/f8/4f/87/f84f8705-6640-a010-29a5-09a23195e41c/mza_453847711009197462.png/60x60bb.jpg", "artworkUrl100":"https://is2-ssl.mzstatic.com/image/thumb/Podcasts113/v4/f8/4f/87/f84f8705-6640-a010-29a5-09a23195e41c/mza_453847711009197462.png/100x100bb.jpg", "collectionPrice":0.00, "trackPrice":0.00, "trackRentalPrice":0, "collectionHdPrice":0, "trackHdPrice":0, "trackHdRentalPrice":0, "releaseDate":"2019-12-10T10:00:00Z", "collectionExplicitness":"cleaned", "trackExplicitness":"cleaned", "trackCount":300, "country":"USA", "currency":"USD", "primaryGenreName":"Society & Culture", "contentAdvisoryRating":"Clean", "artworkUrl600":"https://is2-ssl.mzstatic.com/image/thumb/Podcasts113/v4/f8/4f/87/f84f8705-6640-a010-29a5-09a23195e41c/mza_453847711009197462.png/600x600bb.jpg", "genreIds":["1324", "26"], "genres":["Society & Culture", "Podcasts"]}, 
{"wrapperType":"track", "kind":"podcast", "artistId":364380278, "collectionId":917918570, "trackId":917918570, "artistName":"This American Life", "collectionName":"Serial", "trackName":"Serial", "collectionCensoredName":"Serial", "trackCensoredName":"Serial", "artistViewUrl":"https://podcasts.apple.com/us/artist/wbez/364380278?uo=4", "collectionViewUrl":"https://podcasts.apple.com/us/podcast/serial/id917918570?uo=4", "feedUrl":"http://feeds.serialpodcast.org/serialpodcast", "trackViewUrl":"https://podcasts.apple.com/us/podcast/serial/id917918570?uo=4", "artworkUrl30":"https://is4-ssl.mzstatic.com/image/thumb/Podcasts113/v4/36/8f/43/368f43a6-c97d-f69e-dcae-6c9a3f08b196/mza_3740946593757410045.png/30x30bb.jpg", "artworkUrl60":"https://is4-ssl.mzstatic.com/image/thumb/Podcasts113/v4/36/8f/43/368f43a6-c97d-f69e-dcae-6c9a3f08b196/mza_3740946593757410045.png/60x60bb.jpg", "artworkUrl100":"https://is4-ssl.mzstatic.com/image/thumb/Podcasts113/v4/36/8f/43/368f43a6-c97d-f69e-dcae-6c9a3f08b196/mza_3740946593757410045.png/100x100bb.jpg", "collectionPrice":0.00, "trackPrice":0.00, "trackRentalPrice":0, "collectionHdPrice":0, "trackHdPrice":0, "trackHdRentalPrice":0, "releaseDate":"2018-11-15T10:30:00Z", "collectionExplicitness":"notExplicit", "trackExplicitness":"notExplicit", "trackCount":36, "country":"USA", "currency":"USD", "primaryGenreName":"News", "artworkUrl600":"https://is4-ssl.mzstatic.com/image/thumb/Podcasts113/v4/36/8f/43/368f43a6-c97d-f69e-dcae-6c9a3f08b196/mza_3740946593757410045.png/600x600bb.jpg", "genreIds":["1489", "26", "1488"], "genres":["News", "Podcasts", "True Crime"]}, 
{"wrapperType":"track", "kind":"podcast", "artistId":125443881, "collectionId":214089682, "trackId":214089682, "artistName":"NPR", "collectionName":"Fresh Air", "trackName":"Fresh Air", "collectionCensoredName":"Fresh Air", "trackCensoredName":"Fresh Air", "artistViewUrl":"https://podcasts.apple.com/us/artist/npr/125443881?uo=4", "collectionViewUrl":"https://podcasts.apple.com/us/podcast/fresh-air/id214089682?uo=4", "feedUrl":"https://www.npr.org/rss/podcast.php?id=381444908", "trackViewUrl":"https://podcasts.apple.com/us/podcast/fresh-air/id214089682?uo=4", "artworkUrl30":"https://is3-ssl.mzstatic.com/image/thumb/Podcasts113/v4/d6/9e/e3/d69ee352-84ec-c6c9-ad89-57da3f452ff0/mza_709971845194736840.jpg/30x30bb.jpg", "artworkUrl60":"https://is3-ssl.mzstatic.com/image/thumb/Podcasts113/v4/d6/9e/e3/d69ee352-84ec-c6c9-ad89-57da3f452ff0/mza_709971845194736840.jpg/60x60bb.jpg", "artworkUrl100":"https://is3-ssl.mzstatic.com/image/thumb/Podcasts113/v4/d6/9e/e3/d69ee352-84ec-c6c9-ad89-57da3f452ff0/mza_709971845194736840.jpg/100x100bb.jpg", "collectionPrice":0.00, "trackPrice":0.00, "trackRentalPrice":0, "collectionHdPrice":0, "trackHdPrice":0, "trackHdRentalPrice":0, "releaseDate":"2019-12-09T21:30:00Z", "collectionExplicitness":"notExplicit", "trackExplicitness":"notExplicit", "trackCount":50, "country":"USA", "currency":"USD", "primaryGenreName":"Books", "artworkUrl600":"https://is3-ssl.mzstatic.com/image/thumb/Podcasts113/v4/d6/9e/e3/d69ee352-84ec-c6c9-ad89-57da3f452ff0/mza_709971845194736840.jpg/600x600bb.jpg", "genreIds":["1482", "26", "1301", "1309"], "genres":["Books", "Podcasts", "Arts", "TV & Film"]}, 
{"wrapperType":"track", "kind":"podcast", "collectionId":355187485, "trackId":355187485, "artistName":"Chris Hardwick", "collectionName":"ID10T with Chris Hardwick", "trackName":"ID10T with Chris Hardwick", "collectionCensoredName":"ID10T with Chris Hardwick", "trackCensoredName":"ID10T with Chris Hardwick", "collectionViewUrl":"https://podcasts.apple.com/us/podcast/id10t-with-chris-hardwick/id355187485?uo=4", "feedUrl":"https://rss.art19.com/id10t", "trackViewUrl":"https://podcasts.apple.com/us/podcast/id10t-with-chris-hardwick/id355187485?uo=4", "artworkUrl30":"https://is1-ssl.mzstatic.com/image/thumb/Podcasts123/v4/ce/3f/24/ce3f2466-2a76-a3c8-808b-9ad0e8eb5add/mza_2165967568073271584.jpeg/30x30bb.jpg", "artworkUrl60":"https://is1-ssl.mzstatic.com/image/thumb/Podcasts123/v4/ce/3f/24/ce3f2466-2a76-a3c8-808b-9ad0e8eb5add/mza_2165967568073271584.jpeg/60x60bb.jpg", "artworkUrl100":"https://is1-ssl.mzstatic.com/image/thumb/Podcasts123/v4/ce/3f/24/ce3f2466-2a76-a3c8-808b-9ad0e8eb5add/mza_2165967568073271584.jpeg/100x100bb.jpg", "collectionPrice":0.00, "trackPrice":0.00, "trackRentalPrice":0, "collectionHdPrice":0, "trackHdPrice":0, "trackHdRentalPrice":0, "releaseDate":"2019-12-06T00:43:00Z", "collectionExplicitness":"explicit", "trackExplicitness":"explicit", "trackCount":300, "country":"USA", "currency":"USD", "primaryGenreName":"Comedy Interviews", "contentAdvisoryRating":"Explicit", "artworkUrl600":"https://is1-ssl.mzstatic.com/image/thumb/Podcasts123/v4/ce/3f/24/ce3f2466-2a76-a3c8-808b-9ad0e8eb5add/mza_2165967568073271584.jpeg/600x600bb.jpg", "genreIds":["1496", "26", "1303", "1309"], "genres":["Comedy Interviews", "Podcasts", "Comedy", "TV & Film"]}, 
{"wrapperType":"track", "kind":"podcast", "artistId":125443881, "collectionId":290783428, "trackId":290783428, "artistName":"NPR", "collectionName":"Planet Money", "trackName":"Planet Money", "collectionCensoredName":"Planet Money", "trackCensoredName":"Planet Money", "artistViewUrl":"https://podcasts.apple.com/us/artist/npr/125443881?uo=4", "collectionViewUrl":"https://podcasts.apple.com/us/podcast/planet-money/id290783428?uo=4", "feedUrl":"https://www.npr.org/rss/podcast.php?id=510289", "trackViewUrl":"https://podcasts.apple.com/us/podcast/planet-money/id290783428?uo=4", "artworkUrl30":"https://is4-ssl.mzstatic.com/image/thumb/Podcasts123/v4/68/f0/37/68f037d9-47f0-0120-6dcb-eb0dc07570f6/mza_5572831542089209819.jpg/30x30bb.jpg", "artworkUrl60":"https://is4-ssl.mzstatic.com/image/thumb/Podcasts123/v4/68/f0/37/68f037d9-47f0-0120-6dcb-eb0dc07570f6/mza_5572831542089209819.jpg/60x60bb.jpg", "artworkUrl100":"https://is4-ssl.mzstatic.com/image/thumb/Podcasts123/v4/68/f0/37/68f037d9-47f0-0120-6dcb-eb0dc07570f6/mza_5572831542089209819.jpg/100x100bb.jpg", "collectionPrice":0.00, "trackPrice":0.00, "trackRentalPrice":0, "collectionHdPrice":0, "trackHdPrice":0, "trackHdRentalPrice":0, "releaseDate":"2019-12-07T01:52:00Z", "collectionExplicitness":"notExplicit", "trackExplicitness":"notExplicit", "trackCount":300, "country":"USA", "currency":"USD", "primaryGenreName":"Business", "artworkUrl600":"https://is4-ssl.mzstatic.com/image/thumb/Podcasts123/v4/68/f0/37/68f037d9-47f0-0120-6dcb-eb0dc07570f6/mza_5572831542089209819.jpg/600x600bb.jpg", "genreIds":["1321", "26", "1489"], "genres":["Business", "Podcasts", "News"]}, 
{"wrapperType":"track", "kind":"podcast", "artistId":284341002, "collectionId":283605519, "trackId":283605519, "artistName":"iHeartRadio & HowStuffWorks", "collectionName":"Stuff You Missed in History Class", "trackName":"Stuff You Missed in History Class", "collectionCensoredName":"Stuff You Missed in History Class", "trackCensoredName":"Stuff You Missed in History Class", "artistViewUrl":"https://podcasts.apple.com/us/artist/iheartradio/284341002?uo=4", "collectionViewUrl":"https://podcasts.apple.com/us/podcast/stuff-you-missed-in-history-class/id283605519?uo=4", "feedUrl":"https://feeds.megaphone.fm/stuffyoumissedinhistoryclass", "trackViewUrl":"https://podcasts.apple.com/us/podcast/stuff-you-missed-in-history-class/id283605519?uo=4", "artworkUrl30":"https://is2-ssl.mzstatic.com/image/thumb/Podcasts123/v4/47/e1/db/47e1db56-77ed-e0bd-6b18-86c0700db481/mza_9197234934641735208.png/30x30bb.jpg", "artworkUrl60":"https://is2-ssl.mzstatic.com/image/thumb/Podcasts123/v4/47/e1/db/47e1db56-77ed-e0bd-6b18-86c0700db481/mza_9197234934641735208.png/60x60bb.jpg", "artworkUrl100":"https://is2-ssl.mzstatic.com/image/thumb/Podcasts123/v4/47/e1/db/47e1db56-77ed-e0bd-6b18-86c0700db481/mza_9197234934641735208.png/100x100bb.jpg", "collectionPrice":0.00, "trackPrice":0.00, "trackRentalPrice":0, "collectionHdPrice":0, "trackHdPrice":0, "trackHdRentalPrice":0, "releaseDate":"2019-12-09T14:00:00Z", "collectionExplicitness":"cleaned", "trackExplicitness":"cleaned", "trackCount":300, "country":"USA", "currency":"USD", "primaryGenreName":"History", "contentAdvisoryRating":"Clean", "artworkUrl600":"https://is2-ssl.mzstatic.com/image/thumb/Podcasts123/v4/47/e1/db/47e1db56-77ed-e0bd-6b18-86c0700db481/mza_9197234934641735208.png/600x600bb.jpg", "genreIds":["1487", "26", "1324"], "genres":["History", "Podcasts", "Society & Culture"]}, 
{"wrapperType":"track", "kind":"podcast", "artistId":121664449, "collectionId":1200361736, "trackId":1200361736, "artistName":"The New York Times", "collectionName":"The Daily", "trackName":"The Daily", "collectionCensoredName":"The Daily", "trackCensoredName":"The Daily", "artistViewUrl":"https://podcasts.apple.com/us/artist/the-new-york-times/121664449?uo=4", "collectionViewUrl":"https://podcasts.apple.com/us/podcast/the-daily/id1200361736?uo=4", "feedUrl":"http://rss.art19.com/the-daily", "trackViewUrl":"https://podcasts.apple.com/us/podcast/the-daily/id1200361736?uo=4", "artworkUrl30":"https://is5-ssl.mzstatic.com/image/thumb/Podcasts113/v4/57/9e/80/579e802f-63e7-e5b8-1e2f-8bcb4a1968f7/mza_4646561600001809308.jpeg/30x30bb.jpg", "artworkUrl60":"https://is5-ssl.mzstatic.com/image/thumb/Podcasts113/v4/57/9e/80/579e802f-63e7-e5b8-1e2f-8bcb4a1968f7/mza_4646561600001809308.jpeg/60x60bb.jpg", "artworkUrl100":"https://is5-ssl.mzstatic.com/image/thumb/Podcasts113/v4/57/9e/80/579e802f-63e7-e5b8-1e2f-8bcb4a1968f7/mza_4646561600001809308.jpeg/100x100bb.jpg", "collectionPrice":0.00, "trackPrice":0.00, "trackRentalPrice":0, "collectionHdPrice":0, "trackHdPrice":0, "trackHdRentalPrice":0, "releaseDate":"2019-12-10T10:51:00Z", "collectionExplicitness":"cleaned", "trackExplicitness":"cleaned", "trackCount":300, "country":"USA", "currency":"USD", "primaryGenreName":"Daily News", "contentAdvisoryRating":"Clean", "artworkUrl600":"https://is5-ssl.mzstatic.com/image/thumb/Podcasts113/v4/57/9e/80/579e802f-63e7-e5b8-1e2f-8bcb4a1968f7/mza_4646561600001809308.jpeg/600x600bb.jpg", "genreIds":["1526", "26", "1489"], "genres":["Daily News", "Podcasts", "News"]}, 
{"wrapperType":"track", "kind":"podcast", "artistId":127981066, "collectionId":152249110, "trackId":152249110, "artistName":"WNYC Studios", "collectionName":"Radiolab", "trackName":"Radiolab", "collectionCensoredName":"Radiolab", "trackCensoredName":"Radiolab", "artistViewUrl":"https://podcasts.apple.com/us/artist/wnyc/127981066?uo=4", "collectionViewUrl":"https://podcasts.apple.com/us/podcast/radiolab/id152249110?uo=4", "feedUrl":"http://feeds.wnyc.org/radiolab", "trackViewUrl":"https://podcasts.apple.com/us/podcast/radiolab/id152249110?uo=4", "artworkUrl30":"https://is2-ssl.mzstatic.com/image/thumb/Podcasts123/v4/63/0f/21/630f218b-318f-0372-04bb-56e3a4dcf0f8/mza_561281777130580895.png/30x30bb.jpg", "artworkUrl60":"https://is2-ssl.mzstatic.com/image/thumb/Podcasts123/v4/63/0f/21/630f218b-318f-0372-04bb-56e3a4dcf0f8/mza_561281777130580895.png/60x60bb.jpg", "artworkUrl100":"https://is2-ssl.mzstatic.com/image/thumb/Podcasts123/v4/63/0f/21/630f218b-318f-0372-04bb-56e3a4dcf0f8/mza_561281777130580895.png/100x100bb.jpg", "collectionPrice":0.00, "trackPrice":0.00, "trackRentalPrice":0, "collectionHdPrice":0, "trackHdPrice":0, "trackHdRentalPrice":0, "releaseDate":"2019-11-27T00:35:00Z", "collectionExplicitness":"cleaned", "trackExplicitness":"cleaned", "trackCount":148, "country":"USA", "currency":"USD", "primaryGenreName":"Documentary", "contentAdvisoryRating":"Clean", "artworkUrl600":"https://is2-ssl.mzstatic.com/image/thumb/Podcasts123/v4/63/0f/21/630f218b-318f-0372-04bb-56e3a4dcf0f8/mza_561281777130580895.png/600x600bb.jpg", "genreIds":["1543", "26", "1324", "1533", "1537"], "genres":["Documentary", "Podcasts", "Society & Culture", "Science", "Nature"]}]
}
`

**Comment by mdewilde** [comment]
I'm not sure where you get the `genreId` parameter.

It's not part of Search API documentation: https://affiliate.itunes.apple.com/resources/documentation/itunes-store-web-service-search-api/#searching

Note that the Apple API documentation is also linked from the Search class source code and javadoc: https://github.com/mdewilde/itunes-api/blob/master/src/main/java/be/ceau/itunesapi/Search.java 

In any case, as to your question, it seems Apple returns the same result whether appending `genreId=1303` or not appending it.

To get a response in line with what you pasted here, you would simply write:

```
new Search("podcast")
    .setLimit(10)
    .execute();
```
